### ISSUE TITLE
Pass the HTTP retriever client timeout to the client at creation time

### ISSUE THREAD

**Issue by webignition** [webignition/async-http-retriever#312]
**Is your feature request related to a problem? Please describe.**

`ResourceRetriever` has a `requestTimeout` property which is passed to `Client::send()` at runtime as an option.

We can instead pass the relevant environment variable value to the HTTP client at the time it is created. Doing so simplifies `ResourceRetriever`. The timeout being a HTTP client matter seems more appropriately passed to the client at creation time.

**Describe the solution you'd like**

```yaml
async_http_retriever.http.client.retriever:
    class: GuzzleHttp\Client
    factory: 'App\Services\Http\ClientFactory:create'
    arguments:
        $curlOptions: '%curl_options%'
        $handlerStack: '@async_http_retriever.http.handler_stack.retriever'
        $config:
            cookies: '@GuzzleHttp\Cookie\CookieJarInterface'
            # add the following line
            timeout: '%env(RETRIEVER_TIMEOUT_SECONDS)%'
```
